### PR TITLE
feature(blacklist): all content is now always checked agains blacklisted terms

### PR DESCRIPTION
**Pull request by juho-jaakkola**
- All content is now checked instead of just the 'message' objects
- Checking uses the blacklist in plugin settings instead of hardcoded one
- Checking is done also when updating content instead of just on creation

### CODE REVIEW

**Comment by juho-jaakkola** [comment]
I though all content was being checked for the word blacklist, but in fact only messages were!

This change should make things much more difficult for spammers.

**Comment by mrclay** [comment]
I think it's reasonable to have a separate blacklists for messages. The hardcoded list I suspect would yield a lot of false positives if applied everywhere.

**Comment by juho-jaakkola** [comment]
No, this does it the other way around - this removes the hard-coded list completely and uses just the one defined in plugin settings.

**Comment by juho-jaakkola** [comment]
I suppose we could add two more settings, to make it more flexible and less aggressive:
 - How many blacklisted words are allowed per post
 - The duration of the ban

But maybe in another PR?

**Comment by mrclay** [comment]
As long as the blacklist in settings isn't too broad this is fine. I'd consider the hardcoded list we're removing to be too broad for community discussion posts.

**Pull request merged**
